### PR TITLE
feat(babel): Upgrade Babel to 6

### PR DESCRIPTION
**Pull request by taak77**
- upgrade to Babel 6 and update code based on ES6 spec update
- update other dependencies
- integrate commitizen workflow
- remove Cerebral example

### CODE REVIEW

**Comment by potench** [comment]
:+1: 
- [x] tests are passing 
- [x] adding commitizen with the goal of automating change-logs looks like a good idea 
- [] You could probably just remove `displayName` entirely since it's set by default 
- [] Why did you remove the cerebral example?

**Comment by taak77** [comment]
Will clean up `displayName` with another PR.
i think manual routing example is sufficient and don't feel the need for Cerebral example right now.

**Comment by alanmulhall** [comment]
For the manual example - i see the below error in the console.
`Uncaught TypeError: Cannot read property 'parentNode' of undefined` and status of the tracking requests is "failure", `{type: "pageView", status: "failure", response: Array[2], transactionId: 1}`

**Comment by alanmulhall** [comment]
Looks like the error i mentioned is not specific to this PR, ok to merge.

**Pull request merged**
